
CREATE TABLE [dbo].[SiteApplications](
	[ApplicationID] [int] IDENTITY(1,1) NOT NULL,
	[ParentId] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[TopicOrder] [int] NOT NULL,
	[TopicIndent] [int] NOT NULL,
	[Title] [nvarchar](255) NOT NULL,
	[Heading] [nvarchar](255) NOT NULL,
	[Description] [nvarchar](1000) NOT NULL,
	[HeaderID] [int] NOT NULL,
	[ExtraCSS] [nvarchar](1000) NOT NULL,
	[HRColour] [nvarchar](20) NOT NULL,
	[ShadowColour] [nvarchar](20) NOT NULL,
	[RequiresAuthentication] [bit] NOT NULL,
	[CreationDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NOT NULL,
	[UpdatedBy] [nvarchar](50) NOT NULL,
	[MenuWidth] [int] NOT NULL,
	[SchemeID] [int] NOT NULL,
	[MenuIndex] [int] NOT NULL,
	[ShowInLeftMenu] [bit] NOT NULL,
	[IsTab] [bit] NOT NULL,
	[IsContainer] [bit] NOT NULL,
	[IsClickable] [bit] NOT NULL,
	[TemplateID] [int] NOT NULL,
	[AppURL] [varchar](1000) NOT NULL,
	[SiteID] [int] NOT NULL,
	[ASPXPage] [nvarchar](500) NOT NULL,
	[ASPXIDReq] [bit] NOT NULL,
	[ASPXPath] [varchar](500) NULL,
	[Keywords] [varchar](1000) NOT NULL,
	[ScriptName] [varchar](50) NULL,
	[https] [bit] NOT NULL,
	[Locked] [bit] NULL,
	[Selected] [bit] NOT NULL,
 CONSTRAINT [PK_SiteApplications] PRIMARY KEY CLUSTERED 
(
	[ApplicationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[SiteApplications] ON 
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (1666, 0, N'1', 1, 1, N'Home', N'Home', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2006-02-15T14:03:00.000' AS DateTime), CAST(N'2007-05-24T14:31:00.000' AS DateTime), N'cms-demo', 43, 1, 0, 1, 0, 0, 1, 38, N'', 21, N'', 0, N'', N'', N'home-1666.htm', 0, 0, 1)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (1667, 0, N'1.1', 7, 2, N'About', N'About', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2006-02-15T14:03:00.000' AS DateTime), CAST(N'2007-05-24T14:31:00.000' AS DateTime), N'cms-demo', 40, 1, 0, 1, 0, 0, 1, 38, N'', 21, N'', 0, N'', N'', N'about-1667.htm', 0, 0, 1)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (1668, 0, N'1.2', 8, 2, N'History', N'History', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2006-02-15T14:03:00.000' AS DateTime), CAST(N'2007-05-24T14:31:00.000' AS DateTime), N'cms-demo', 47, 1, 0, 1, 0, 0, 1, 38, N'', 21, N'', 0, N'', N'', N'history-1668.htm', 0, 0, 1)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (1669, 0, N'1.2.1', 9, 3, N'News', N'News', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2006-02-15T14:03:00.000' AS DateTime), CAST(N'2007-05-24T14:31:00.000' AS DateTime), N'cms-demo', 41, 1, 0, 1, 0, 0, 1, 38, N'', 21, N'', 0, N'', N'', N'', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (1670, 0, N'1.2.2', 10, 3, N'Contact', N'Contact', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2006-02-15T14:03:00.000' AS DateTime), CAST(N'2007-05-24T14:31:00.000' AS DateTime), N'cms-demo', 51, 1, 0, 1, 0, 0, 1, 38, N'', 21, N'', 0, N'', N'', N'contact-1670.htm', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (1671, 0, N'1.2.3', 15, 3, N'Address & Map', N'Address & Map', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2006-02-15T15:49:00.000' AS DateTime), CAST(N'2007-05-24T14:31:00.000' AS DateTime), N'cms-demo', 120, 1, 0, 1, 0, 0, 1, 38, N'', 21, N'', 0, N'', N'', N'address---map.htm', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (1672, 0, N'1.3', 18, 2, N'Contact Form', N'Contact Form', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2006-02-15T15:50:00.000' AS DateTime), CAST(N'2007-05-24T14:31:00.000' AS DateTime), N'cms-demo', 83, 1, 0, 1, 0, 0, 1, 38, N'', 21, N'', 0, N'', N'', N'', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (1673, 0, N'1.3.1', 20, 3, N'Company', N'Company', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2006-02-15T15:55:00.000' AS DateTime), CAST(N'2007-05-24T14:31:00.000' AS DateTime), N'cms-demo', 120, 1, 0, 1, 0, 0, 1, 38, N'', 21, N'', 0, N'', N'', N'company-1673.htm', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (1674, 0, N'1.3.2', 21, 3, N'Our Services', N'Our Services', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2006-02-15T15:55:00.000' AS DateTime), CAST(N'2007-05-24T14:31:00.000' AS DateTime), N'cms-demo', 120, 1, 0, 1, 0, 0, 1, 38, N'', 21, N'', 0, N'', N'', N'our-services.htm', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (1675, 0, N'1.3.3', 22, 3, N'Site Map', N'Site Map', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2006-02-15T15:55:00.000' AS DateTime), CAST(N'2007-05-24T14:31:00.000' AS DateTime), N'cms-demo', 56, 1, 0, 0, 0, 0, 1, 38, N'', 21, N'', 0, N'', N'', N'site-map-1675.htm', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (1676, 0, N'2', 29, 1, N'Privacy Policy', N'Privacy Policy', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2006-02-15T15:56:00.000' AS DateTime), CAST(N'2007-05-24T14:31:00.000' AS DateTime), N'cms-demo', 82, 1, 0, 0, 0, 0, 1, 38, N'', 21, N'', 0, N'', N'', N'privacy-policy.htm', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (1677, 0, N'2.1', 37, 2, N'Terms of Use', N'Terms of Use', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2006-02-15T15:56:00.000' AS DateTime), CAST(N'2007-05-24T14:31:00.000' AS DateTime), N'cms-demo', 84, 1, 0, 0, 0, 0, 1, 38, N'', 21, N'', 0, N'', N'', N'terms-of-use.htm', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (1678, 0, N'2.1.1', 37, 3, N'Search Results', N'Search Results', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2006-02-15T16:26:00.000' AS DateTime), CAST(N'2007-05-24T14:31:00.000' AS DateTime), N'cms-demo', 94, 1, 0, 0, 0, 0, 1, 38, N'', 21, N'', 0, N'', N'', N'', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (1679, 0, N'2.1.2', 38, 3, N'Events', N'Events', N'Events Calendar', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2006-02-15T16:27:00.000' AS DateTime), CAST(N'2007-05-24T14:31:00.000' AS DateTime), N'cms-demo', 46, 1, 0, 1, 0, 0, 1, 38, N'', 21, N'', 0, N'', N'Events', N'', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2319, 0, N'2.2', 40, 2, N'Test 1', N'Test 1', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2007-05-25T17:06:00.000' AS DateTime), CAST(N'2007-05-25T17:07:00.000' AS DateTime), N'cms-demo', 43, 1, 0, 0, 0, 0, 0, 38, N'', 21, N'', 0, N'', N'', N'test-1.htm', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2321, 0, N'1.2.3.1', 16, 4, N'Test 2', N'Test 2', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2007-05-25T17:06:00.000' AS DateTime), CAST(N'2007-05-25T17:51:00.000' AS DateTime), N'cms-demo', 43, 1, 0, 0, 0, 0, 0, 38, N'', 21, N'', 0, N'', N'', N'test-2.htm', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2324, 0, N'2.2.2', 28, 3, N'Test 2', N'Test 2', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2007-05-25T17:06:00.000' AS DateTime), CAST(N'2007-05-25T17:51:00.000' AS DateTime), N'cms-demo', 43, 1, 0, 0, 0, 0, 0, 38, N'', 21, N'', 0, N'', N'', N'test-2.htm', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2327, 1666, N'A1', 33, 1, N'A1', N'A1', N'', 0, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2013-03-17T06:58:00.000' AS DateTime), CAST(N'2013-03-17T06:58:00.000' AS DateTime), N'cms-demo', 0, 0, 0, 0, 0, 0, 0, 0, N'', 0, N'', 0, N'', N'', N'', 0, 0, 1)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2328, 2327, N'A2', 31, 2, N'A2', N'A2', N'', 0, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2013-03-17T06:59:00.000' AS DateTime), CAST(N'2013-03-17T06:59:00.000' AS DateTime), N'cms-demo', 0, 0, 0, 0, 0, 0, 0, 0, N'', 0, N'', 0, N'', N'', N'', 0, 0, 1)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2329, 2328, N'A3', 31, 2, N'A3', N'A3', N'', 0, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2013-03-17T06:59:00.000' AS DateTime), CAST(N'2013-03-17T06:59:00.000' AS DateTime), N'cms-demo', 0, 0, 0, 0, 0, 0, 0, 0, N'', 0, N'', 0, N'', N'', N'', 0, 0, 1)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2330, 2329, N'A4', 32, 2, N'A4', N'A4', N'', 0, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2013-03-17T06:59:00.000' AS DateTime), CAST(N'2013-03-17T06:59:00.000' AS DateTime), N'cms-demo', 0, 0, 0, 0, 0, 0, 0, 0, N'', 0, N'', 0, N'', N'', N'', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2331, 2330, N'A5', 33, 2, N'A5', N'A5', N'', 0, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2013-03-18T00:04:00.000' AS DateTime), CAST(N'2013-03-18T00:04:00.000' AS DateTime), N'cms-demo', 0, 0, 0, 0, 0, 0, 0, 0, N'', 0, N'', 0, N'', N'', N'', 0, 0, 1)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2332, 0, N'A6', 48, 2, N'A6', N'A6', N'', 0, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2013-03-18T00:04:00.000' AS DateTime), CAST(N'2013-03-18T00:04:00.000' AS DateTime), N'cms-demo', 0, 0, 0, 0, 0, 0, 0, 0, N'', 0, N'', 0, N'', N'', N'', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2333, 2330, N'a7', 42, 1, N'a7', N'a7', N'', 0, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2013-03-18T07:05:00.000' AS DateTime), CAST(N'2013-03-18T07:05:00.000' AS DateTime), N'cms-demo', 0, 0, 0, 0, 0, 0, 0, 0, N'', 0, N'', 0, N'', N'', N'', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2334, 2327, N'A8', 32, 1, N'A8', N'A8', N'', 0, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2013-03-18T07:06:00.000' AS DateTime), CAST(N'2013-03-18T07:06:00.000' AS DateTime), N'cms-demo', 0, 0, 0, 0, 0, 0, 0, 0, N'', 0, N'', 0, N'', N'', N'', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2335, 0, N'EEEEE', 42, 1, N'EEEEE', N'EEEEE', N'', 0, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2013-03-18T13:52:00.000' AS DateTime), CAST(N'2013-03-18T13:52:00.000' AS DateTime), N'cms-demo', 0, 0, 0, 0, 0, 0, 0, 0, N'', 0, N'', 0, N'', N'', N'', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2336, 0, N'AA', 44, 2, N'AA', N'AA', N'', 0, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2013-03-18T13:52:00.000' AS DateTime), CAST(N'2013-03-18T13:52:00.000' AS DateTime), N'cms-demo', 0, 0, 0, 0, 0, 0, 0, 0, N'', 0, N'', 0, N'', N'', N'', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2338, 0, N'NIGHT', 43, 1, N'NIGHT', N'NIGHT', N'', 0, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2013-03-17T06:58:00.000' AS DateTime), CAST(N'2013-03-17T06:58:00.000' AS DateTime), N'cms-demo', 0, 0, 0, 0, 0, 0, 0, 0, N'', 0, N'', 0, N'', N'', N'', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2339, 2336, N'TEST3', 23, 4, N'TEST3', N'TEST3', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2007-05-25T17:06:00.000' AS DateTime), CAST(N'2007-05-25T17:51:00.000' AS DateTime), N'cms-demo', 43, 1, 0, 0, 0, 0, 0, 38, N'', 21, N'', 0, N'', N'', N'test-2.htm', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2340, 2334, N'test', 33, 1, N'test', N'test', N'', 1, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2006-02-15T14:03:00.000' AS DateTime), CAST(N'2007-05-24T14:31:00.000' AS DateTime), N'cms-demo', 43, 1, 0, 1, 0, 0, 1, 38, N'', 21, N'', 0, N'', N'', N'home-1666.htm', 0, 0, 0)
GO
INSERT [dbo].[SiteApplications] ([ApplicationID], [ParentId], [Name], [TopicOrder], [TopicIndent], [Title], [Heading], [Description], [HeaderID], [ExtraCSS], [HRColour], [ShadowColour], [RequiresAuthentication], [CreationDate], [ModifiedDate], [UpdatedBy], [MenuWidth], [SchemeID], [MenuIndex], [ShowInLeftMenu], [IsTab], [IsContainer], [IsClickable], [TemplateID], [AppURL], [SiteID], [ASPXPage], [ASPXIDReq], [ASPXPath], [Keywords], [ScriptName], [https], [Locked], [Selected]) VALUES (2341, 2330, N'a77', 41, 1, N'a77', N'a77', N'', 0, N'', N'#a0a0a0', N'#cccccc', 0, CAST(N'2013-03-18T07:05:00.000' AS DateTime), CAST(N'2013-03-18T07:05:00.000' AS DateTime), N'cms-demo', 0, 0, 0, 0, 0, 0, 0, 0, N'', 0, N'', 0, N'', N'', N'', 0, 0, 0)
GO
SET IDENTITY_INSERT [dbo].[SiteApplications] OFF
GO
ALTER TABLE [dbo].[SiteApplications] ADD  CONSTRAINT [DF_SiteApplications_ParentId]  DEFAULT ((0)) FOR [ParentId]
GO
ALTER TABLE [dbo].[SiteApplications] ADD  CONSTRAINT [DF_SiteApplications_Selected]  DEFAULT ((0)) FOR [Selected]
GO
/****** Object:  StoredProcedure [dbo].[SiteApplicationsLastMainMenu]    Script Date: 3/6/2025 10:24:29 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
 
CREATE PROCEDURE [dbo].[SiteApplicationsLastMainMenu]AS BEGIN  SELECT TOP 1 * FROM dbo.SiteApplications where ParentId=0 order by TopicOrder desc;END
GO
